Update Jenkinsfile

diff --git a/integracion/jenkinsfile b/integracion/jenkinsfile
--- a/integracion/jenkinsfile
+++ b/integracion/jenkinsfile
@@ -1,1 +1,195 @@
-
+pipeline {
+    agent any
+    tools {
+        gradle "gradle-7.6"
+        nodejs "node"
+    }
+    environment {
+        TESTPLAN = "IXR-94"
+        TAG = "@TEST_IXR-93"
+    }
+    stages {
+        stage('CleanWorkspace') {
+            steps {
+                cleanWs()
+            }
+        }
+        /*stage('Develop Branch') {
+          steps {
+            git branch: 'develop', url: 'https://github.com/dbustamanter/prueba.dibrsite.com.git'
+    	    script {
+    	      def currentBranch = env.{BRANCH_NAME}
+    	      if (currentBranch == 'develop') { 
+                echo "El commit proviene de la rama 'develop'."
+    	      } else {
+                currentBuild.result = 'ABORTED'
+                error("El commit no proviene de la rama 'develop'. Abortando.")
+                }
+            }
+          }
+        }*/
+        /*stage('git clone'){
+            steps {
+                git branch: 'develop', url: 'https://github.com/dbustamanter/prueba.dibrsite.com.git'
+                echo env.BRANCH_NAME
+                script {
+                    env.TOKEN = sh(
+                        script: 'curl -H "Content-Type: application/json" -X POST --data @"integracion/cloud_auth.json" https://xray.cloud.getxray.app/api/v2/authenticate | tr -d "\\""',
+                        returnStdout: true
+                    ).trim()
+                    sh 'export TOKEN=$TOKEN'
+                }
+            }
+        }*/
+        stage('gitClone') {
+          steps {
+            //checkout([$class: ‘GitSCM’, branches: [[name: ‘origin/develop’]], userRemoteConfigs: [[url: ‘https://github.com/dbustamanter/prueba.dibrsite.com.git’]]])
+            git branch: 'develop', url: 'https://github.com/dbustamanter/prueba.dibrsite.com.git'
+            script {
+              env.TOKEN = sh(
+                script: 'curl -H "Content-Type: application/json" -X POST --data @"integracion/cloud_auth.json" https://xray.cloud.getxray.app/api/v2/authenticate | tr -d "\\""',
+                returnStdout: true
+              ).trim()
+              sh 'export TOKEN=$TOKEN'
+            }
+          }
+          post {
+            success {
+              echo 'La clonación del repositorio ha sido exitosa'
+              sh '''sed -i 's/"summary": "TITULOJSON"/"summary": "Clonacion exitosa"/g' integracion/jira.json'''
+              sh '''
+              curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-passed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+              '''
+            }
+            failure {
+              echo 'La clonación del repositorio ha fallado'
+              sh '''sed -i 's/"summary": "TITULOJSON"/"summary": "Clonacion fallida"/g' integracion/jira.json'''
+              sh '''
+              curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-failed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+              '''
+            }
+          }
+        }
+        stage('Pruebas unitarias') {
+        steps {
+            echo "$TESTPLAN"
+            echo "$TAG"
+            sh 'npm install'
+            script {
+                try {
+                    def testResult = sh(returnStdout: true, script: 'npm test || exit 1')
+                    echo "Resultado de la prueba: ${testResult}"
+                } catch (err) {
+                    if (err instanceof hudson.AbortException && err.getMessage().contains("exit code 1")) {
+                        echo "La prueba falló. Por favor, revise su código."
+                        sh '''sed -i 's/"summary": "Clonacion exitosa"/"summary": "Prueba unitaria fallida"/g' integracion/jira.json'''
+                        sh '''
+                        curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-failed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+                        '''
+                        throw err
+                    } else {
+                        echo "Prueba exitosa"
+                        throw err
+                    }
+                }
+                sh '''sed -i 's/"summary": "Clonacion exitosa"/"summary": "Prueba unitaria exitosa"/g' integracion/jira.json'''
+                sh '''
+                curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-passed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+                '''
+            }
+        }
+    }
+    stage('Deploy QA') {
+      steps {
+        sh 'cp -r $WORKSPACE/* /var/www/html/qa'
+      }
+      post {
+        success {
+          echo 'El despliegue al ambiente QA ha sido exitoso'
+          sh '''sed -i 's/"summary": "Prueba unitaria exitosa"/"summary": "Despliegue QA exitoso"/g' integracion/jira.json'''
+          sh '''
+          curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-passed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+          '''
+        }
+        failure {
+          echo 'El despliegue al ambiente QA ha fallado'
+          sh '''sed -i 's/"summary": "Prueba unitaria exitosa"/"summary": "Despliegue QA fallido"/g' integracion/jira.json'''
+          sh '''
+          curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-failed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+          '''
+        }
+      }
+    }
+    stage('Automatizacion') {
+      steps {
+        cleanWs()
+        git branch: 'master', url: 'https://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@github.com/dbustamanter/Healenium_POC.git'
+        //sh 'git clone -b integracionXray https://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@github.com/dbustamanter/Healenium_POC.git'
+        //sh 'cd /Healenium_POC'
+        sh 'pwd'
+        sh 'gradle runWithCucumber -P tags=@TEST_IXR-93'
+        sh 'ls'
+        /*sh '''
+        curl --location --request POST 'https://integracionx-ray.atlassian.net/rest/api/3/issue/IXR-94/attachments' \
+        --header 'Authorization: Basic YWFyb24uYmFycmFAdHNvZnRsYXRhbS5jb206QVRBVFQzeEZmR0YwZzBzSm5rVmNfZnRsTmVHV3RzaDFUN2pCVE9HRkNnZ0V2LUVwNk1fMHI2M1AzUDBvUHR4SmdhaDZwWjZ4b2xsbmdkZ1FGU0tVUWtGdER2TzZlLWJRVEdJbW5EcVBSMEtVQ3NnUGVYNHk0bmY2QUZXSGVuOTJ5ZlpXS2k0U3RKdUNKb2duZWdESkZDc2xESHZBdmZlY1NEMk8wTVZmOVZBM3lHN2tsQUY3OHE0PUM2MTMxQzAx' \
+        --header 'Content-Type: application/json' \
+        --header 'X-Atlassian-Token: no-check' \
+        --form 'file=@"results/reporteQA.pdf"'
+		''' */
+        sh 'chmod +x tokenXray.sh'
+        sh './tokenXray.sh'
+        sh 'cd results && export tempUrl=$(cat url.txt) && curl -H \'Authorization: Basic ZGllZ28uYnVzdGFtYW50ZUB0c29mdGxhdGFtLmNvbTpBVEFUVDN4RmZHRjBHemVnNFV1Ui1CYmFRczl4Ql9jUEo3SFpyN1VqQ214RG95blA2dGZUU0lCa25ubThIVEtGQ0NUMGx2VjU5X0UtTGlMZzE0RFlCVzQ4d0dEZHlYVGxVODc5OEFLeFhldHhHQUZaT1k1UnNJcEtuNkNTOXczdnNoeXdEb0Jkb1BKSlFHbk9JRlhCZjVIY25MYlJOT1BKRlNsT0dRemxsNF9RSUpTN0JSR3RxVU09QzAxNTU0MTk=\' -X POST $tempUrl  -H \"Content-Type:multipart/form-data\" -H \'X-Atlassian-Token: no-check\' -F \'file=@"reporteQA.pdf\"\' && rm url.txt'
+      }
+    }
+    stage('Merge Master') {
+      steps {
+        cleanWs()
+        git branch: 'develop', url: 'https://github.com/dbustamanter/prueba.dibrsite.com.git'
+        sh "git config --global user.email 'Tsoft@tsoftglobal.com'"
+        sh "git config --global user.name 'Tsoft'"
+        sh "git checkout testing2"
+        sh "git merge --no-ff -m 'Merge de cambios de develop' develop"
+        sh "git push -f https://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@github.com/dbustamanter/prueba.dibrsite.com.git testing2"
+      }
+      post {
+        success {
+          echo 'La migracion ha sido exitosa'
+          sh '''sed -i 's/"summary": "TITULOJSON"/"summary": "Migracion exitosa"/g' integracion/jira.json'''
+          sh '''
+          curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-passed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+          '''
+        }
+        failure {
+          echo 'La migracion ha fallado.'
+          sh '''sed -i 's/"summary": "TITULOJSON"/"summary": "Migracion fallida"/g' integracion/jira.json'''
+          sh '''
+          curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-failed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+          '''
+        }
+      }
+    }
+    stage('Deploy Prod') {
+      steps {
+        cleanWs()
+        git branch: 'testing2', url: 'https://github.com/dbustamanter/prueba.dibrsite.com.git'
+        sh 'cp -r $WORKSPACE/* /var/www/html/prod'
+      }
+    post {
+        success {
+          echo 'El despliegue al ambiente PROD ha sido exitoso'
+          sh '''sed -i 's/"summary": "Despliegue QA exitoso"/"summary": "Despliegue PROD exitoso"/g' integracion/jira.json'''
+          sh '''
+          curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-passed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+          '''
+        }
+        failure {
+          echo 'El despliegue al ambiente PROD ha fallado'
+          sh '''sed -i 's/"summary": "Despliegue QA exitoso"/"summary": "Despliegue PROD fallido"/g' integracion/jira.json'''
+          sh '''
+          curl -H "Content-Type: multipart/form-data" -X POST -F info=@integracion/jira.json -F results=@integracion/prueba-failed.json -H "Authorization: Bearer $TOKEN" https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
+          '''
+        }
+      }
+    }
+  }
+}
